# IndexError -- It happens when we try to access the index which is out of range

a = [1,2,3]
a[4]   # Index is upto 2 so it will throw an IndexError
print(a)

